# Generated by Django 5.1.7 on 2025-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='registration',
            field=models.CharField(db_index=True, max_length=11),
        ),
    ]
