# Generated by Django 5.1.7 on 2025-03-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_myuser_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isDirectFollow',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
