# Generated by Django 5.1.7 on 2025-03-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_myinstitution_userinstution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInstution',
            new_name='UserInstitution',
        ),
    ]
