# Generated by Django 5.1.7 on 2025-03-20 09:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_rename_userinstution_userinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the club')),
                ('is_public', models.BooleanField(default=True, help_text='If False, users need approval to join')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='rest_api.myinstitution')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_club', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='rest_api_cl_name_9ce055_idx'), models.Index(fields=['institution'], name='rest_api_cl_institu_433477_idx')],
            },
        ),
    ]
