# Generated by Django 5.1.7 on 2025-03-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='is_public',
        ),
    ]
