# Generated by Django 5.1.7 on 2025-03-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_types',
            field=models.IntegerField(blank=True, choices=[(1, 'Follow Request'), (2, 'Like'), (3, 'Comment'), (4, 'Club Post')], null=True),
        ),
    ]
